---

- name: Create custom fact directory
  file:
    path: "{{ facts__dir|d('/etc/ansible/facts.d') }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: ['prometheus-exporter', 'prometheus-exporter-facts']

- name: Insert custom fact file
  template:
    src: prometheus_exporter.facts.py.j2
    dest: "{{ facts__dir|d('/etc/ansible/facts.d') }}/{{ prometheus_exporter__name }}.fact"
    owner: root
    group: root
    mode: 0755
  tags: ['prometheus-exporter', 'prometheus-exporter-facts']
