---

- name: 'Install {{ prometheus_exporter__name }} sysvinit service unit file'
  template:
    src: prometheus_exporter.sysvinit.j2
    dest: '/etc/init.d/{{ prometheus_exporter__service_name }}'
    owner: root
    group: root
    mode: 0750
  when: ansible_service_mgr == 'sysvinit'
  notify: ['restart-{{ prometheus_exporter__tag_name }}']

- name: 'Install {{ prometheus_exporter__name }} systemd service unit file'
  template:
    src: prometheus_exporter.systemd.j2
    dest: '/etc/systemd/system/{{ prometheus_exporter__service_name }}.service'
    owner: root
    group: root
    mode: 0640
  when: ansible_service_mgr == 'systemd'
  register: _prometheus_exporter__service_systemd
  notify: ['restart-{{ prometheus_exporter__tag_name }}']

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: _prometheus_exporter__service_systemd is changed
  changed_when: true

- name: 'Ensure {{ prometheus_exporter__service_name }} is started and enabled on boot'
  service:
    name: '{{ prometheus_exporter__service_name }}'
    enabled: '{{ prometheus_exporter__service_enabled|bool }}'
    state: "{{ prometheus_exporter__service_enabled|bool|ternary('started', 'stopped') }}"
