---

- name: Run role
  hosts: all
  any_errors_fatal: true
  roles:
    - role: turgon37.prometheus_exporter
      vars:
        prometheus_exporter__name: node_exporter
    - role: turgon37.prometheus_exporter
      vars:
        prometheus_exporter__name: mysqld_exporter
        prometheus_exporter__download_url:
          "https://github.com/prometheus/mysqld_exporter/releases/download/\
          v{{ prometheus_exporter__version }}/\
          mysqld_exporter-{{ prometheus_exporter__version }}.linux\
          -{{ prometheus_exporter__go_arch_map[ansible_architecture]|d(ansible_architecture) }}.tar.gz"
